### ISSUE TITLE
Add a section for language proposals and discussion

### ISSUE THREAD

**Issue by parlough** [parlough/thisweekindart#18]
Language changes are commonly being discussed in issues, PRs, and in-progress proposals on the [Dart language repository](https://github.com/dart-lang/language). Many developers don't know what potential features are in the pipeline. We should consider highlighting some that are currently being discussed.

**Comment by JulianBissekkou** [comment]
I like this idea 👍🏽

**Comment by parlough** [comment]
I've been including this for a few issues now :)
