### ISSUE TITLE
package: `custom_lint`

### ISSUE THREAD

**Issue by Luckey-Elijah** [parlough/thisweekindart#20]
A relatively new package for writing custom a custom dart analyzer has been released. It's certainly in early development, but some worth look considering adding to TWID.

[`custom_lint`](https://pub.dev/packages/custom_lint)

**Comment by parlough** [comment]
Thanks for sharing! I will definitely include it in the next issue :)

**Comment by parlough** [comment]
Thanks so much for the suggestion. `package:custom_lint` is exciting and I'm excited to see more third-party packages introduce their own relevant lints in the future. I've included it in [Issue 10](https://thisweekindart.dev/issues/issue-10)!
